module.exports = require('@testing-library/jest-dom');

// Mock electronAPI
global.electronAPI = {
  getUserInfo: jest.fn(),
  saveUserInfo: jest.fn(),
  updateWeight: jest.fn(),
  getAllExercises: jest.fn(),
  getExerciseByName: jest.fn(),
  addExercise: jest.fn(),
  deleteExercise: jest.fn(),
  saveActivity: jest.fn(),
  getActivitiesByDate: jest.fn(),
  getRecentActivities: jest.fn(),
  getTodayStats: jest.fn(),
  getHistoryStats: jest.fn(),
  getStreakDays: jest.fn(),
  getReminderSettings: jest.fn(),
  getReminderSetting: jest.fn(),
  updateReminderSettings: jest.fn(),
  pauseReminders: jest.fn(),
  resumeReminders: jest.fn(),
  getReminderStatus: jest.fn(),
  getSystemSetting: jest.fn(),
  setSystemSetting: jest.fn(),
  getAutoStart: jest.fn(),
  setAutoStart: jest.fn(),
  getGlobalMinInterval: jest.fn(),
  setGlobalMinInterval: jest.fn(),
  showMainWindow: jest.fn(),
  showSettingsWindow: jest.fn(),
  showReminder: jest.fn(),
  closeReminder: jest.fn(),
  onReminderTrigger: jest.fn(),
  removeAllListeners: jest.fn(),
};
